vim.keymap.set("n", "<leader>h", [[<cmd>lua require("harpoon.ui").toggle_quick_menu()<CR>]], {noremap =true})
vim.keymap.set("n", "<leader>j", [[<cmd>lua require("harpoon.ui").nav_file(1)<CR>]], {noremap =true})
vim.keymap.set("n", "<leader>k", [[<cmd>lua require("harpoon.ui").nav_file(2)<CR>]], {noremap =true})
vim.keymap.set("n", "<leader>l", [[<cmd>lua require("harpoon.ui").nav_file(3)<CR>]], {noremap =true})
vim.keymap.set("n", "<leader>a", [[<cmd>lua require("harpoon.mark").add_file()<CR>]], {noremap =true})
